model {
  file: "model.sdf"
  file_format {
    version {
      major: 1
      minor: 6
    }
    name: "sdf"
  }
}
name: "coro_allie_sensor_config_1"
description: "Allie is a medium sized skid steer robot with 3d lidar, cameras and other sensors."
authors {
  name: "Kevin Knoedler"
  email: "ak619@lafn.org"
}

